export enum LinkBioThemeEnum {
  summer = "summer",
  winter = "winter",
  fall = "fall",
  snow = "snow",
  wine = "wine",
  modern = "modern",
  pastel = "pastel",
  floral = "floral",
  urban = "urban",
  sunset = "sunset",
  pureWhite = "pureWhite",
  greenForest = "greenForest",
  navyBlue = "navyBlue",
  retro = "retro",
  royalPurple = "royalPurple",
  earthTone = "earthTone",
  coolGray = "coolGray",
  vibrantRed = "vibrantRed",
  sunnyDay = "sunnyDay",
  classicBlack = "classicBlack",
}
