import { ITheme } from "./IThemeData";
import { LinkBioThemeEnum } from "./ThemeTypeEnum";

export class ThemeData implements ITheme {
  public name: string;
  public primaryColor: string;
  public secondaryColor: string;
  public backgroundColor: string;
  public buttonPrimaryColor: string;
  public whiteColor: string;
  public textPrimaryColor: string;
  public textSecondaryColor: string;
  public audioProgressColor: string;
  public audioIconColor: string;
  public backgroundImage: string;
  public bottomImage: string;

  constructor({
    name,
    primaryColor,
    secondaryColor,
    backgroundColor,
    buttonPrimaryColor,
    whiteColor,
    textPrimaryColor,
    textSecondaryColor,
    audioProgressColor,
    audioIconColor,
    backgroundImage,
    bottomImage,
  }: ITheme) {
    this.name = name;
    this.primaryColor = primaryColor;
    this.secondaryColor = secondaryColor;
    this.backgroundColor = backgroundColor;
    this.buttonPrimaryColor = buttonPrimaryColor;
    this.whiteColor = whiteColor;
    this.textPrimaryColor = textPrimaryColor;
    this.textSecondaryColor = textSecondaryColor;
    this.audioProgressColor = audioProgressColor;
    this.audioIconColor = audioIconColor;
    this.backgroundImage = backgroundImage;
    this.bottomImage = bottomImage;
  }
}

export const DefaultThemes: Record<LinkBioThemeEnum, ThemeData> = {
  [LinkBioThemeEnum.summer]: new ThemeData({
    name: "summer",
    primaryColor: "#cde5fb",
    secondaryColor: "#63AEDC",
    backgroundColor: "#B7DAF6",
    buttonPrimaryColor: "#57a0e1",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#000000",
    textSecondaryColor: "#757575",
    audioProgressColor: "#57a0e1",
    audioIconColor: "#57a0e1",
    backgroundImage: "/assets/summer/images/summer-background.png",
    bottomImage: "/assets/summer/images/summer-bottom.png",
  }),
  [LinkBioThemeEnum.winter]: new ThemeData({
    name: "winter",
    primaryColor: "#002f68",
    secondaryColor: "#3162BE",
    backgroundColor: "#06213C",
    buttonPrimaryColor: "#153F7A",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#FFFFFF",
    textSecondaryColor: "#BDBDBD",
    audioProgressColor: "#3162BE",
    audioIconColor: "#3162BE",
    backgroundImage: "/assets/winter/images/winter-background.png",
    bottomImage: "/assets/winter/images/winter-bottom.png",
  }),
  [LinkBioThemeEnum.fall]: new ThemeData({
    name: "fall",
    primaryColor: "#FCD09C",
    secondaryColor: "#FEF1D2",
    backgroundColor: "#F7B071",
    buttonPrimaryColor: "#FE963F",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#424242",
    textSecondaryColor: "#757575",
    audioProgressColor: "#FE963F",
    audioIconColor: "#FE963F",
    backgroundImage: "/assets/fall/images/fall-background.png",
    bottomImage: "/assets/fall/images/fall-bottom.png",
  }),
  [LinkBioThemeEnum.snow]: new ThemeData({
    name: "snow",
    primaryColor: "#F59E95",
    secondaryColor: "#F0F0F0",
    backgroundColor: "#ebd4d3",
    buttonPrimaryColor: "#F59E95",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#F59E95",
    textSecondaryColor: "#757575",
    audioProgressColor: "#B0C4DE",
    audioIconColor: "#F59E95",
    backgroundImage: "/assets/snow/images/snow-background.png",
    bottomImage: "/assets/snow/images/snow-bottom.png",
  }),
  [LinkBioThemeEnum.wine]: new ThemeData({
    name: "wine",
    primaryColor: "#B22222",
    secondaryColor: "#7A1C1C",
    backgroundColor: "#7A1C1C",
    buttonPrimaryColor: "#B22222",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#EDE0DC",
    textSecondaryColor: "#B22222",
    audioProgressColor: "#D9B8A3",
    audioIconColor: "#B22222",
    backgroundImage: "/assets/wine/images/wine-background.png",
    bottomImage: "/assets/wine/images/wine-bottom.png",
  }),
  [LinkBioThemeEnum.modern]: new ThemeData({
    name: "modern",
    primaryColor: "#282828",
    secondaryColor: "#333333",
    backgroundColor: "#1E1E1E",
    buttonPrimaryColor: "#00C7E5",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#E0E0E0",
    textSecondaryColor: "#757575",
    audioProgressColor: "#00C7E5",
    audioIconColor: "#00C7E5",
    backgroundImage: "/assets/modern/images/modern-background.png",
    bottomImage: "/assets/modern/images/modern-bottom.png",
  }),
  [LinkBioThemeEnum.pastel]: new ThemeData({
    name: "pastel",
    primaryColor: "#F5E6CC",
    secondaryColor: "#B8D8D8",
    backgroundColor: "#F2F2F2",
    buttonPrimaryColor: "#E2B4B4",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#4A4A4A",
    textSecondaryColor: "#757575",
    audioProgressColor: "#E2B4B4",
    audioIconColor: "#B8D8D8",
    backgroundImage: "/assets/pastel/images/pastel-background.png",
    bottomImage: "/assets/pastel/images/pastel-bottom.png",
  }),
  [LinkBioThemeEnum.floral]: new ThemeData({
    name: "floral",
    primaryColor: "#F8F3EC",
    secondaryColor: "#C4DFAA",
    backgroundColor: "#D3E4CD",
    buttonPrimaryColor: "#F5B0C7",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#5E548E",
    textSecondaryColor: "#90A4AE",
    audioProgressColor: "#F5B0C7",
    audioIconColor: "#C4DFAA",
    backgroundImage: "/assets/floral/images/floral-background.png",
    bottomImage: "/assets/floral/images/floral-bottom.png",
  }),
  [LinkBioThemeEnum.urban]: new ThemeData({
    name: "urban",
    primaryColor: "#E5E5E5",
    secondaryColor: "#9B9B9B",
    backgroundColor: "#3A3A3A",
    buttonPrimaryColor: "#5B7A8B",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#FFFFFF",
    textSecondaryColor: "#BDBDBD",
    audioProgressColor: "#5B7A8B",
    audioIconColor: "#E5E5E5",
    backgroundImage: "/assets/urban/images/urban-background.png",
    bottomImage: "/assets/urban/images/urban-bottom.png",
  }),
  [LinkBioThemeEnum.sunset]: new ThemeData({
    name: "sunset",
    primaryColor: "#FCD34D",
    secondaryColor: "#F97316",
    backgroundColor: "#EF4444",
    buttonPrimaryColor: "#FCD34D",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#FFFFFF",
    textSecondaryColor: "#FCD34D",
    audioProgressColor: "#F97316",
    audioIconColor: "#FCD34D",
    backgroundImage: "/assets/sunset/images/sunset-background.png",
    bottomImage: "/assets/sunset/images/sunset-bottom.png",
  }),
  [LinkBioThemeEnum.pureWhite]: new ThemeData({
    name: "pureWhite",
    primaryColor: "#FFFFFF",
    secondaryColor: "#F5F5F5",
    backgroundColor: "#FAFAFA",
    buttonPrimaryColor: "#007AFF",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#000000",
    textSecondaryColor: "#8E8E93",
    audioProgressColor: "#C7C7CC",
    audioIconColor: "#007AFF",
    backgroundImage: "/assets/purewhite/images/purewhite-background.png",
    bottomImage: "/assets/purewhite/images/purewhite-bottom.png",
  }),
  [LinkBioThemeEnum.greenForest]: new ThemeData({
    name: "greenForest",
    primaryColor: "#4C7B4C",
    secondaryColor: "#6A9A6A",
    backgroundColor: "#3D683D",
    buttonPrimaryColor: "#8EBE8E",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#FFFFFF",
    textSecondaryColor: "#BDBDBD",
    audioProgressColor: "#FFFFFF",
    audioIconColor: "#8EBE8E",
    backgroundImage: "/assets/greenforest/images/greenforest-background.png",
    bottomImage: "/assets/greenforest/images/greenforest-bottom.png",
  }),
  [LinkBioThemeEnum.navyBlue]: new ThemeData({
    name: "navyBlue",
    primaryColor: "#2C3E50",
    secondaryColor: "#34495E",
    backgroundColor: "#2C3E50",
    buttonPrimaryColor: "#3498DB",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#ECF0F1",
    textSecondaryColor: "#BDC3C7",
    audioProgressColor: "#3498DB",
    audioIconColor: "#ECF0F1",
    backgroundImage: "/assets/navyblue/images/navyblue-background.png",
    bottomImage: "/assets/navyblue/images/navyblue-bottom.png",
  }),
  [LinkBioThemeEnum.retro]: new ThemeData({
    name: "retro",
    primaryColor: "#C7C7A8",
    secondaryColor: "#B5B59C",
    backgroundColor: "#D6D6BC",
    buttonPrimaryColor: "#904245",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#5C5C42",
    textSecondaryColor: "#7D7D6A",
    audioProgressColor: "#904245",
    audioIconColor: "#E5B53B",
    backgroundImage: "/assets/retro/images/retro-background.png",
    bottomImage: "/assets/retro/images/retro-bottom.png",
  }),
  [LinkBioThemeEnum.royalPurple]: new ThemeData({
    name: "royalPurple",
    primaryColor: "#6A0572",
    secondaryColor: "#821389",
    backgroundColor: "#5A0063",
    buttonPrimaryColor: "#FFC000",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#FFFFFF",
    textSecondaryColor: "#F7E2FF",
    audioProgressColor: "#FFC000",
    audioIconColor: "#FFFFFF",
    backgroundImage: "/assets/royalpurple/images/royalpurple-background.png",
    bottomImage: "/assets/royalpurple/images/royalpurple-bottom.png",
  }),
  [LinkBioThemeEnum.earthTone]: new ThemeData({
    name: "earthTone",
    primaryColor: "#C29B7E",
    secondaryColor: "#D0C3B7",
    backgroundColor: "#B8865D",
    buttonPrimaryColor: "#4C4A43",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#4C4A43",
    textSecondaryColor: "#7A7974",
    audioProgressColor: "#4C4A43",
    audioIconColor: "#B8865D",
    backgroundImage: "/assets/earthtone/images/earthtone-background.png",
    bottomImage: "/assets/earthtone/images/earthtone-bottom.png",
  }),
  [LinkBioThemeEnum.coolGray]: new ThemeData({
    name: "coolGray",
    primaryColor: "#878787",
    secondaryColor: "#C0C0C0",
    backgroundColor: "#BDBDBD",
    buttonPrimaryColor: "#333333",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#333333",
    textSecondaryColor: "#5C5C5C",
    audioProgressColor: "#333333",
    audioIconColor: "#BDBDBD",
    backgroundImage: "/assets/coolgray/images/coolgray-background.png",
    bottomImage: "/assets/coolgray/images/coolgray-bottom.png",
  }),
  [LinkBioThemeEnum.vibrantRed]: new ThemeData({
    name: "vibrantRed",
    primaryColor: "#E55D5D",
    secondaryColor: "#F28B8B",
    backgroundColor: "#E55D5D",
    buttonPrimaryColor: "#B71C1C",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#FFFFFF",
    textSecondaryColor: "#FCE4EC",
    audioProgressColor: "#B71C1C",
    audioIconColor: "#FFFFFF",
    backgroundImage: "/assets/vibrantred/images/vibrantred-background.png",
    bottomImage: "/assets/vibrantred/images/vibrantred-bottom.png",
  }),
  [LinkBioThemeEnum.sunnyDay]: new ThemeData({
    name: "sunnyDay",
    primaryColor: "#FFFDD0",
    secondaryColor: "#FAD16B",
    backgroundColor: "#FFE599",
    buttonPrimaryColor: "#D69800",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#5A5A5A",
    textSecondaryColor: "#BDBDBD",
    audioProgressColor: "#D69800",
    audioIconColor: "#5A5A5A",
    backgroundImage: "/assets/sunnyday/images/sunnyday-background.png",
    bottomImage: "/assets/sunnyday/images/sunnyday-bottom.png",
  }),
  [LinkBioThemeEnum.classicBlack]: new ThemeData({
    name: "classicBlack",
    primaryColor: "#000000",
    secondaryColor: "#1C1C1C",
    backgroundColor: "#000000",
    buttonPrimaryColor: "#FDD835",
    whiteColor: "#FFFFFF",
    textPrimaryColor: "#FFFFFF",
    textSecondaryColor: "#D3D3D3",
    audioProgressColor: "#FDD835",
    audioIconColor: "#FFFFFF",
    backgroundImage: "/assets/classicblack/images/classicblack-background.png",
    bottomImage: "/assets/classicblack/images/classicblack-bottom.png",
  }),
};

export const allDefaulThemes: ThemeData[] = Object.values(DefaultThemes);
